@startuml
start
:User executes add command on home page;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command is in invalid format])
    :Show invalid command format as error message;

else ([else])
    if () then ([course name is invalid])
    : Show invalid course name error message;
    else ([else])
        if () then ([course already exists])
        : Show duplicate course error message;
        else ([else])
        : Add the course to the course list;
        : Display the updated course list;
        endif
    endif
endif
stop

@enduml
