@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CodeSphereParser" as CodeSphereParser LOGIC_COLOR
participant ":DeleteCourseCommandParser" as DeleteCourseCommandParser LOGIC_COLOR
participant "d:DeleteCourseCommand" as DeleteCourseCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> CodeSphereParser : parseCommand("delete 1")
activate CodeSphereParser

create DeleteCourseCommandParser
CodeSphereParser -> DeleteCourseCommandParser
activate DeleteCourseCommandParser

DeleteCourseCommandParser --> CodeSphereParser
deactivate DeleteCourseCommandParser

CodeSphereParser -> DeleteCourseCommandParser : parse("1")
activate DeleteCourseCommandParser

create DeleteCourseCommand
DeleteCourseCommandParser -> DeleteCourseCommand
activate DeleteCourseCommand

DeleteCourseCommand --> DeleteCourseCommandParser : d
deactivate DeleteCourseCommand

DeleteCourseCommandParser --> CodeSphereParser : d
deactivate DeleteCourseCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCourseCommandParser -[hidden]-> CodeSphereParser
destroy DeleteCourseCommandParser

CodeSphereParser --> LogicManager : d
deactivate CodeSphereParser

LogicManager -> DeleteCourseCommand : execute()
activate DeleteCourseCommand

DeleteCourseCommand -> Model : deleteCourse(1)
activate Model

Model --> DeleteCourseCommand
deactivate Model

create CommandResult
DeleteCourseCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCourseCommand
deactivate CommandResult

DeleteCourseCommand --> CodeSphereParser : result
deactivate DeleteCourseCommand

CodeSphereParser --> LogicManager : result
deactivate CodeSphereParser

[<--LogicManager
deactivate LogicManager
@enduml
