@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package StorageUML {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "CourseList Storage" #F4F6F6{
Class "<<interface>>\nCourseListStorage" as CourseListStorage
Class JsonCourseListStorage
Class JsonSerializableCourseList
Class JsonAdaptedCourse
Class JsonAdaptedStudent
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" CourseListStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> CourseListStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonCourseListStorage ..|> CourseListStorage
JsonCourseListStorage ..> JsonSerializableCourseList
JsonSerializableCourseList --> "*" JsonAdaptedCourse
JsonAdaptedCourse --> "*" JsonAdaptedStudent
JsonAdaptedStudent --> "*" JsonAdaptedTag

@enduml
