@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow

Class DisplayPanel
Class SplashPanel
Class CombinedPanel
Class CourseListPanel
Class CourseCard
Class StudentListPanel
Class StudentCard

Class ResultDisplay
Class StatusBarFooter
Class CommandBox
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

package StageManager <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .up.|> Ui
UiManager -down--> "1" MainWindow
UiManager -right> Logic


MainWindow -up-> "0..1" HelpWindow

MainWindow *-left->  "1" CommandBox
MainWindow *-left-> "1" ResultDisplay
MainWindow *-left-> "1" StatusBarFooter

MainWindow *-down-> "1" DisplayPanel

DisplayPanel *-down-> "0...1" SplashPanel
DisplayPanel *-down-> "0...1" CombinedPanel
DisplayPanel *-down-> "0...1" CourseListPanel

MainWindow -right> Logic
MainWindow -right> StageManager

CombinedPanel *-down-> "1" StudentListPanel
CombinedPanel *-right-> "1" CourseListPanel

CourseListPanel -down-> "*" CourseCard
CourseCard .right.> Model
StudentListPanel -down-> "*" StudentCard
StudentCard .right.> Model

'hidden arrows for organisation
SplashPanel -[hidden]right- CombinedPanel
CommandBox -[hidden]down- ResultDisplay
CommandBox -[hidden]down-- StatusBarFooter
Logic -[hidden]down-- StageManager
@enduml
